# Generated by Django 5.2.3 on 2025-06-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_is_business"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="grade",
            field=models.CharField(default="c", max_length=10),
        ),
    ]
